### ISSUE TITLE
feat: Optional Environment Variable for `.httplaceholder`

### ISSUE THREAD

**Issue by tomershvueli** [dukeofharen/httplaceholder#232] opened 2022-04-09 22:12 UTC
# Feature Request

I'm trying to package HttPlaceholder for [Cloudron](https://www.cloudron.io/), which has a read-only filesystem. Right now I'm having issues since HttPlaceholder fails to create the `.httplaceholder` directory. It'd be great if I could set an environment variable like `httplaceholderDirectoryLocation` to give it a directory that it can write to. 

**Describe Preferred Solution**

Provide an optional environment variable similar to the ones [already defined here](https://github.com/dukeofharen/httplaceholder/blob/master/docs/docs.md#environment-variables). 

**Describe Alternatives**

An alternative could be an option for HttPlaceholder to write in the current directory its in. 

**Related Code**

Unsure, but this is the error I'm currently getting: 
```
Apr 09 18:09:34 2022-04-09 22:09:34.505 +00:00 [FTL] Host terminated unexpectedly
Apr 09 18:09:34 System.IO.IOException: Read-only file system : '/home/cloudron/.httplaceholder'
Apr 09 18:09:34 at System.IO.FileSystem.CreateDirectory(String fullPath)
Apr 09 18:09:34 at System.IO.Directory.CreateDirectory(String path)
Apr 09 18:09:34 at HttPlaceholder.Infrastructure.Implementations.FileService.CreateDirectory(String path) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Implementations/FileService.cs:line 30
Apr 09 18:09:34 at HttPlaceholder.Infrastructure.Configuration.ConfigurationParser.EnsureDefaultValuesAreAdded(IDictionary`2 argsDictionary) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Configuration/ConfigurationParser.cs:line 124
Apr 09 18:09:34 at HttPlaceholder.Infrastructure.Configuration.ConfigurationParser.ParseConfiguration(String[] args) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Configuration/ConfigurationParser.cs:line 54
Apr 09 18:09:34 at HttPlaceholder.Utilities.ProgramUtilities.BuildWebHost(String[] args) in /builds/ducode/httplaceholder/src/HttPlaceholder/Utilities/ProgramUtilities.cs:line 71
Apr 09 18:09:34 at HttPlaceholder.Program.Main(String[] args) in /builds/ducode/httplaceholder/src/HttPlaceholder/Program.cs:line 18
```

**Additional Context**

None. But I really appreciate all the hard work that went into HttPlaceholder! This is exactly what I was looking for and it works great! 

**If the feature request is approved, would you be willing to submit a PR?**
I could try if I get some assistance with where the relevant code is in the repo, but I've never worked on .NET before :)

**Comment by dukeofharen** [comment] 2022-04-10 07:09
Hi @tomershvueli,

Thanks for your kind words :) 
Have you already tried using the environment variable [fileStorageLocation](https://github.com/dukeofharen/httplaceholder/blob/master/docs/docs.md#file-store-optional=)? This should be what you looking for. Let me know if it works.

**Comment by dukeofharen** [comment] 2022-04-10 10:34
Hmm, I checked it, and it seems that even when you set the "fileStorageLocation", it still tries to create a folder ".httplaceholder" in the home directory. This is not expected behavior and this is a bug.

**Comment by tomershvueli** [comment] 2022-04-10 13:31
Yeah it wasn't explicitly clear in the documentation that if I were to set `fileStorageLocation` it wouldn't try to create the `.httplaceholder` in the home directory, so I wasn't sure if this was a bug or feature. Looks like it's the former. Do you think this is a reasonable fix?

**Comment by dukeofharen** [comment] 2022-04-10 14:39
@tomershvueli This is not a hard fix. I will take a look at it.

**Comment by dukeofharen** [comment] 2022-04-10 15:30
I created a PR: https://github.com/dukeofharen/httplaceholder/pull/233. I will release the fix if the build is OK.

**Comment by tomershvueli** [comment] 2022-04-17 16:38
@dukeofharen thanks for your patience. I just got around to testing out the latest but I'm still seeing a similar issue. With the same setup, this is the error I'm now getting: 
```
Apr 17 12:36:08 2022-04-17 16:36:08.910 +00:00 [FTL] Host terminated unexpectedly
Apr 17 12:36:08 System.IO.IOException: Read-only file system : '/root/.httplaceholder'
Apr 17 12:36:08 at System.IO.FileSystem.CreateDirectory(String fullPath)
Apr 17 12:36:08 at System.IO.Directory.CreateDirectory(String path)
Apr 17 12:36:08 at HttPlaceholder.Infrastructure.Implementations.FileService.CreateDirectory(String path) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Implementations/FileService.cs:line 30
Apr 17 12:36:08 at HttPlaceholder.Infrastructure.Configuration.ConfigurationParser.SetDefaultFileStorageLocation(IDictionary`2 argsDictionary) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Configuration/ConfigurationParser.cs:line 134
Apr 17 12:36:08 at HttPlaceholder.Infrastructure.Configuration.ConfigurationParser.EnsureDefaultValuesAreAdded(IDictionary`2 argsDictionary) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Configuration/ConfigurationParser.cs:line 105
Apr 17 12:36:08 at HttPlaceholder.Infrastructure.Configuration.ConfigurationParser.ParseConfiguration(String[] args) in /builds/ducode/httplaceholder/src/HttPlaceholder.Infrastructure/Configuration/ConfigurationParser.cs:line 54
Apr 17 12:36:08 at HttPlaceholder.Utilities.ProgramUtilities.BuildWebHost(String[] args) in /builds/ducode/httplaceholder/src/HttPlaceholder/Utilities/ProgramUtilities.cs:line 71
Apr 17 12:36:08 at HttPlaceholder.Program.Main(String[] args) in /builds/ducode/httplaceholder/src/HttPlaceholder/Program.cs:line 18
```

Note that this does slightly differ from the original error in that it references the path `/root/.httplaceholder` instead of `/home/cloudron/.httplaceholder`. Let me know if I'm missing something.

**Comment by dukeofharen** [comment] 2022-04-18 15:11
@tomershvueli Just for checking:
- You are running version `v1.4.2.681`?
- You have set the configuration value [fileStorageLocation](https://github.com/dukeofharen/httplaceholder/blob/master/docs/docs.md#file-store-optional=) to a custom value?

You should start HttPlaceholder like this: `httplaceholder -V --fileStorageLocation "/path/to/stubsfolder"`. The `.httplaceholder` should not be created if you provide this variable. The `-V` flag is used to enable verbose logging.

HttPlaceholder retrieves, when starting the application and you have not specified the `fileStorageLocation`, the user home folder and creates a `.httplaceholder` folder in it. When HttPlaceholder tries to create a folder in the `/root` folder, it probably means that you try to run HttPlaceholder as root.

Can you check and verify if it works? If it does not work, can you maybe turn on [verbose logging](https://github.com/dukeofharen/httplaceholder/blob/master/docs/docs.md#verbose-output=) and share the full logs?

**Comment by dukeofharen** [comment] 2022-04-18 15:42
@tomershvueli I think I might have found another bug... It seems that when you specify the `fileStorageLocation` as environment variable, the application does not use this value and tries to create a default folder in the user home folder, which causes your error. I think you are trying to set the value using an environment variable?

I might need to take a look at the configuration of HttPlaceholder in general, as it seems to be a bit too complex (at least in code).

**Comment by tomershvueli** [comment] 2022-04-19 01:20
Well whaddaya know? That was exactly it! I was using `fileStorageLocation` as an environment variable, but when using it as an argument when running HttPlaceholder it worked great! For my purposes we can close the issue as there is a known workaround (use the argument instead of environment variable), but I'll leave that to you in case you do want to rework some of the internal logic. 
Thanks for digging into this and your work on HttPlaceholder!

**Comment by dukeofharen** [comment] 2022-04-19 19:42
Yes, thanks and nice to hear @tomershvueli! I will create a new ticket for this bug and will close this one.

**Closed by dukeofharen** 2022-04-19 19:42 UTC
Labels: enhancement, bugfix
